name: workflow for actions

on: 
  push:
  workflow_dispatch:

jobs:
  job-1:
    name: job-1
    runs-on: ubuntu-latest
    steps:
      - name: commands
        run: |
            pwd
            ls -ltr
      - name: Checkout
        uses: actions/checkout@v6.0.0
      - name: step-3 commands
        run: |
            echo 'pwd' >> myartifacts.txt
            mkdir artifact
            pwd
            echo 'hostname' >> artifact/hostname.txt
            echo 'ls -ltr' >> artifact/listfiles.txt

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
            name: myfiles
            path: myartifacts.txt
            
      - name: upload artifacts directory
        uses: actions/upload-artifact@v4
        with:
            name: mydirectory
            path: |
             ./myartifacts.txt
             artifact

      - name: upload artifacts directory with exclusion using !**
        uses: actions/upload-artifact@v4
        with:
            name: mydirectory
            path: |
             ./myartifacts.txt
             artifact
             !** hostname.txt # for ignoring any files, give the name
