name: workflow for actions

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  job-1:
    name: job-1
    runs-on: ubuntu-latest
    steps:
      - name: commands
        run: |
            pwd
            ls -ltr
      - name: Checkout
        uses: actions/checkout@v6.0.0
      - name: step-3 commands
        run: |
            echo 'pwd' >> myartifacts.txt
            mkdir artifact
            pwd
            echo 'hostname' >> artifact/hostname.txt
            echo 'ls -ltr' >> artifact/listfiles.txt

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
            name: myfiles
            path: myartifacts.txt
            
      - name: upload artifacts directory
        uses: actions/upload-artifact@v4
        with:
            name: mydirectory
            path: |
             ./myartifacts.txt
             artifact

      - name: upload artifacts directory with exclusion using !**
        uses: actions/upload-artifact@v4
        with:
            name: upload-${{ github.run_id }}-${{ github.job }}
            path: |
             ./myartifacts.txt
             artifact/
             !**/hostname.txt
  job-2:
      name: job-2
      needs: job-1
      runs-on: ubuntu-latest
      steps:
      - name: download artifacts from job1
        uses: actions/download-artifact@v4
        with:
            name: myfiles
      - name: list the file
        run: 
              ls -ltr

  job-3:
      name: job-3
      needs: job-2
      runs-on: ubuntu-latest
      steps:
      - name: create folder/dir
        run: mkdir -p myfolder
      - name: download artifacts from job1
        uses: actions/download-artifact@v4
        with:
            name: myfiles
            path: myfolder
      - name: list the file
        run: 
              ls -ltr
      - name: exit in continue-on-error
        run: exit 1
