name: Docker_build_image

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2
      - name: setup python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.11"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          mkdir -p report
          PYTHONPATH=. pytest -v \
          --cov=. --cov-report=xml:report/coverage.xml \
          --cov-report=term-missing \
          --junitxml=report/test-results.xml
          ls -ltr
      - name: upload report
        uses: actions/upload-artifact@v7.0.0
        with:
          name: unit-test-report
          path: report/

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test]
    outputs:
      image_tag: ${{ steps.vars.outputs.IMAGE_TAGS }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: generate tags
        id: vars
        run: |
          IMAGE_TAGS="${{ github.run_id }}-${{ github.sha }}"
          echo "IMAGE_TAGS=${IMAGE_TAGS}" >> $GITHUB_OUTPUT

      - name: build docker image 
        uses: docker/build-push-action@v5 
        with: 
          context: . 
          push: false 
          load: true 
          tags: my_app:${{ steps.vars.outputs.IMAGE_TAGS }}
          
      - name: save image
        run: |
          mkdir -p image-tag
          docker save my_app:${{ steps.vars.outputs.IMAGE_TAGS }} -o image-tag/image.tar

      - name: upload image tag
        uses: actions/upload-artifact@v7.0.0
        with:
          name: image-tag
          path: image-tag/

  publish-dockerhub:
    name: Publish to DockerHub
    runs-on: ubuntu-latest
    needs: [build]
    env:
      IMAGE_TAGS: ${{ needs.build.outputs.image_tag }}

    steps:

      - name: download image tag
        uses: actions/download-artifact@v7.0.0
        with:
          name: image-tag
          path: .

      - name: load docker image
        run: |
          docker load -i image.tar

      - name: login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUBUSER }}
          password: ${{ secrets.DOCKERHUBPASS }}

      - name: push docker image.
        run: |
          docker tag my_app:${{ env.IMAGE_TAGS }} andydoc49/my_app:${{ env.IMAGE_TAGS }}
          docker push andydoc499/my_app:${{ env.IMAGE_TAGS }}
