name: myworkflow
# to get trigger on every push
on: push

jobs:
  job1:
    name: myjob1
    runs-on: ubuntu-latest
    steps:
      - name: say hi
        run: echo "hi all"
      - name: check the os version
        run: cat etc/os-release
      
