name: myworkflow
# to get trigger on every push
on: push

jobs:
  job1:
    name: myjob1
    runs-on: ubuntu-latest
    steps:
      - name: say hi
        run: echo "hi all"
      - name: check the os version
        run: cat /etc/os-release

  job2:
    name: job2
    runs-on: unbuntu-latest
    steps:
      - name: check hostname
        run: hostname
      - name: display date
        run: date
  job3:
    name: job3
    needs: job1    #create dependency using needs so that job3 will run after 1
    runs-on: ubuntu-latest
    steps:
       - name: echo
         run: echo "hello job3"
       - name: sleep
         run: sleep 10
  job4:
    name: job4
    needs: [job1, job2, job3]  #create dependency using needs so that job3 will run after 1
    runs-on: windows-latest
    steps:
       - name: check runner
         shell: pwsh
         run: get-computerinfo
       - name: sleep
         run: sleep 10
    
      
