name: Demo_variables

on: 

  workflow_dispatch:

env:
  App_name: demoapp
  App_user: demouser
  App_port: 44

jobs:
  job-1:
      name: job-1
      runs-on: ubuntu-latest
      steps:
      - name: Environment variables
        run: echo "[INFO] appication name is $App_name user is $App_user and port is $App_port."
      - name: secrets
        run: echo "[INFO] app login pass is ${{secrets.App_password}} "   
      - name: context and built-in variables
        run: |
            echo "[INFO] repository name: ${{github.repository}}"
            echo "[INFO] committed by: ${{github.actor}}"
            echo "[INFO] branch: ${{github.ref}}"
            echo "[INFO] runners details: ${{runner.name}}"
            echo "[INFO] event details: ${{github.event_name}}"
            echo "[INFO] runners os: ${{runner.os}}"
            echo "[INFO] job ID: ${{job.check_run_id}}"
            
  job-2:  
      name: job-2
      runs-on: ubuntu-latest
      steps:
      - name: create files/folder
        run: |
          mkdir -p folder
          echo "hello aniket" >> folder/file1.txt
          ls -ltr
      - name: commands
        uses: actions/upload-artifact@v4
        with:
            name: files
            path: folder
      - name: list the file
        run: 
              ls -ltr
